### ISSUE TITLE
Script Bugs

### ISSUE THREAD

**Issue by nubnub4455** [xF4b3r/krunker.io-hack#49]
While in a game of Krunker and trying out the hotkeys, nothing happened. No fancy UI telling me where the bad guys are, no B hopping, no nothing. I was pretty upset about this. I checked the script in tampermonkey and it showed a few script bugs (mainly unexpected comma uses and something about a case block). Since I'm not a coding genius and Google tells me nothing, I need someone on here to help me.

**Comment by Jytesh** [comment]
You need to turn on the script and when u start it tells you click to play. don’t click hacks in the right side and your welcome

**Comment by ZippyMagician** [comment]
>  mainly unexpected comma uses and something about a case block
Hate to tell you this, but these are not bugs. These are "problems" with formatting (that have no effect on the output of the script) They are recommendations and nothing more, and are NOT contributing to the script not executing on krunker. Make sure the script is actually on when you go on the website, which is most likely the problem here.
